name: Quality Checks

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20' 
      - name: Install Dependencies
        run: npm install
      - name: Run npm audit
        run: npm audit  
      - name: Check Lint
        run: npm run lint:fix
      - name: Format code
        run: npm run format