name: Security Checks

on: [push, pull_request]

jobs:
  scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:    
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run gitleaks security scan
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'
          
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
          REPOSITORY: ctse-product-service
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          cd product_service
          docker build -t $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT      

      - name: Run Docker Scout security scan
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: quickview,cves,recommendations
          only-severities: critical,high
          sarif-file: scout-report.sarif
          to-latest: true
          ignore-base: true
          ignore-unchanged: true
          only-fixed: true

      - name: Upload Docker Scout report
        uses: actions/upload-artifact@v2
        with:
          name: docker-scout-findings
          path: scout-report.sarif

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: docker-scout-findings
          path: scout-report.sarif
